/* Generated by tools/i18n/make_demo_strings.py — do not edit by hand.
   Guide's own words here are the Android app's localised strings,
   not a second translation of them. */
window.UMMAHTI_I18N = {
 "guide": [
  {
   "q": "cemas",
   "rtl": false,
   "title": "Kecemasan dan Kegelisahan",
   "cat": "Hati & Perasaan",
   "why": "Satu kata sehari-hari. Tidak perlu tahu istilah pencarian lebih dulu, dan tidak perlu hafal daftar topik.",
   "sources": [
    {
     "ref": "Al-Qur’an 13:28",
     "tag": "Mulai di sini",
     "note": "Menyatakan bahwa hati menjadi tenteram dengan mengingat Allah."
    },
    {
     "ref": "Al-Qur’an 94:5-6"
    },
    {
     "ref": "Al-Qur’an 2:286"
    },
    {
     "ref": "Sahih al-Bukhari 6363",
     "note": "Nabi ﷺ senantiasa berlindung kepada Allah dari kegundahan dan kesedihan, dari kelemahan dan kemalasan, dari kekikiran dan kepengecutan, dari beban utang dan dari tekanan orang lain.",
     "tag": "Sahih"
    }
   ],
   "step": "Kembalilah pada zikir yang pendek dan sederhana saat pikiran berpacu: beberapa kata pun, diulang-ulang."
  },
  {
   "q": "mengulangi dosa",
   "rtl": false,
   "title": "Kembali pada Dosa yang Sama",
   "cat": "Iman & Taubat",
   "why": "Ditulis sebagaimana diucapkan, tanpa kata kunci. Katalognya memuat ungkapan yang benar-benar diketik orang.",
   "sources": [
    {
     "ref": "Al-Qur’an 3:135",
     "tag": "Mulai di sini",
     "note": "Memuji orang yang bila menzalimi diri lalu mengingat Allah dan tidak bersikeras padahal mereka tahu."
    },
    {
     "ref": "Al-Qur’an 39:53"
    },
    {
     "ref": "Al-Qur’an 4:110"
    },
    {
     "ref": "Sahih al-Bukhari 7507",
     "note": "Dalam sebuah riwayat dari Nabi ﷺ, seorang hamba berbuat dosa lalu memohon ampun, kemudian berbuat dosa lagi dan memohon lagi, dan setiap kali Allah berfirman bahwa hamba-Nya tahu ia memiliki Tuhan yang mengampuni dosa dan menghisabnya, lalu Dia mengampuninya.",
     "tag": "Sahih"
    }
   ],
   "step": "Bertaubatlah lagi, tanpa menganggap taubat sebelumnya sia-sia. Ia tidak sia-sia."
  },
  {
   "q": "gagal ujian",
   "rtl": false,
   "title": "Gagal Ujian",
   "cat": "Kerja, Belajar & Rezeki",
   "why": "Situasi sehari-hari, bukan istilah keagamaan. Dan jawabannya menyebut sumbernya lengkap.",
   "sources": [
    {
     "ref": "Al-Qur’an 2:216",
     "tag": "Mulai di sini",
     "note": "Menyatakan bahwa boleh jadi Anda membenci sesuatu yang baik bagi Anda; Allah mengetahui, sedang Anda tidak."
    },
    {
     "ref": "Al-Qur’an 3:139"
    },
    {
     "ref": "Al-Qur’an 94:5-6"
    },
    {
     "ref": "Sahih Muslim 2664",
     "note": "Nabi ﷺ bersabda: bersungguh-sungguhlah pada apa yang bermanfaat bagimu, mintalah pertolongan Allah dan jangan lemah; jika sesuatu menimpamu, jangan berkata “seandainya aku berbuat begini”, tetapi katakan: Allah telah menetapkan dan berbuat apa yang Dia kehendaki.",
     "tag": "Sahih"
    }
   ],
   "step": "Cari tahu persis apa yang keliru, dan perlakukan itu sebagai informasi, bukan identitas."
  },
  {
   "q": "hutang",
   "rtl": false,
   "title": "Utang",
   "cat": "Kerja, Belajar & Rezeki",
   "why": "Satu kata. Pencocokan berjalan di ponsel Anda, dan apa yang Anda ketik tidak pernah meninggalkannya.",
   "sources": [
    {
     "ref": "Al-Qur’an 2:280",
     "tag": "Mulai di sini",
     "note": "Memerintahkan memberi tenggang kepada yang berutang dan kesulitan, serta menyebut membebaskannya lebih baik."
    },
    {
     "ref": "Al-Qur’an 65:7",
     "note": "Menyatakan bahwa Allah akan mendatangkan kemudahan setelah kesulitan."
    },
    {
     "ref": "Al-Qur’an 2:275"
    },
    {
     "ref": "Sahih al-Bukhari 6363",
     "note": "Nabi ﷺ senantiasa berlindung kepada Allah dari kegundahan dan kesedihan, dari kelemahan dan kemalasan, dari kekikiran dan kepengecutan, dari beban utang dan dari tekanan orang lain.",
     "tag": "Sahih"
    }
   ],
   "step": "Tuliskan jumlah utuhnya dan buat rencana pelunasan, sepelan apa pun. Angka yang disebutkan lebih kecil daripada angka yang ditakuti."
  },
  {
   "q": "keputusan sulit",
   "rtl": false,
   "title": "Keputusan Sulit (Istikharah)",
   "cat": "Hidup & Keputusan",
   "why": "Menjawab dengan apa yang bisa dirujuk saja. Tidak mengeluarkan fatwa dan tidak memberi hukum.",
   "sources": [
    {
     "ref": "Al-Qur’an 3:159",
     "tag": "Mulai di sini",
     "note": "Memerintahkan bertawakal kepada Allah setelah keputusan diambil."
    },
    {
     "ref": "Al-Qur’an 2:216",
     "note": "Menyatakan bahwa boleh jadi Anda membenci sesuatu yang baik bagi Anda; Allah mengetahui, sedang Anda tidak."
    },
    {
     "ref": "Al-Qur’an 65:3"
    },
    {
     "ref": "Sahih al-Bukhari 1166",
     "note": "Nabi ﷺ mengajarkan para sahabatnya salat dan doa khusus untuk memohon petunjuk Allah sebelum mengambil keputusan.",
     "tag": "Sahih"
    }
   ],
   "step": "Salatlah sunah sesuai kemampuan, lalu panjatkan doa istikharah menurut pemahaman Anda."
  }
 ],
 "search": [
  {
   "q": "mal qariah",
   "hit": "Al-Qaari’a · Surah 101",
   "sub": "Hari Kiamat",
   "why": "Huruf Latin, dieja menurut bunyinya. Tidak perlu papan ketik Arab."
  },
  {
   "q": "ayat kursi",
   "hit": "Al-Baqarah 255",
   "sub": "Ayat Kursi",
   "why": "Dengan nama yang dipakai orang, bukan nomornya."
  },
  {
   "q": "2:255",
   "hit": "Al-Baqarah 255",
   "sub": "Surah Al-Baqarah",
   "why": "Rujukan ayat biasa."
  },
  {
   "q": "yasin",
   "hit": "Yaasiin · Surah 36",
   "sub": "Ya-Sin, Yasin, Yaseen",
   "why": "Ejaan-ejaan dari satu bunyi Arab menyatu."
  },
  {
   "q": "sedekah",
   "hit": "Sedekah",
   "sub": "Ayat-ayat tentang menafkahkan harta di jalan Allah",
   "why": "Sebuah topik, dengan nama apa pun: zakat, infak, صدقة."
  },
  {
   "q": "الرحمن",
   "rtl": true,
   "hit": "Ar-Rahmaan · Surah 55",
   "sub": "Yang Maha Pengasih",
   "why": "Bahasa Arab, dengan atau tanpa harakat."
  }
 ],
 "themes": {},
 "copy": {
  "copy": "Salin",
  "copied": "Tersalin",
  "manual": "Tekan Ctrl+C"
 }
};
